import { copyFileSync, readdirSync, renameSync, statSync, unlinkSync, writeFileSync } from "fs";
import { basename, join } from "path";
import {
  CONVERTED_DIR,
  env,
  log,
  plainText,
  selectPodcastEpisodeMetadata,
  type PodcastEpisodeMetadata,
} from "./lib";

export type { PodcastEpisodeMetadata } from "./lib";

export const DEFAULT_FEED_FILENAME = "podrush-feed.xml";
export const DEFAULT_FEED_TITLE = "Podrush Private Podcast";
export const DEFAULT_FEED_DESCRIPTION = "Speed-adjusted podcast episodes generated by Podrush.";
export const FEED_COVER_FILENAME = "cover.png";
export const FEED_COVER_SOURCE_PATH = join("static", FEED_COVER_FILENAME);

export type PodcastFeedConfig = {
  publicBaseUrl: string;
  feedFilename: string;
  feedTitle: string;
  feedDescription: string;
  uploadTarget: string;
};

export type ConvertedPodcastFile = {
  filename: string;
  path: string;
  episodeId: number;
  speed: number;
  speedLabel: string;
  size: number;
  mtime: Date;
};

export type PodcastFeedItem = ConvertedPodcastFile & {
  title: string;
  description: string;
  pubDate: Date;
  enclosureUrl: string;
  guid: string;
  durationSecs: number | null;
  metadata: PodcastEpisodeMetadata | null;
};

export type PodcastFeedStatus = {
  feedPath: string;
  feedFilename: string;
  publicFeedUrl: string;
  publicBaseUrl: string;
  configuredPublicBaseUrl: boolean;
  uploadTarget: string;
  configuredUploadTarget: boolean;
  generatedAt: string;
  itemCount: number;
  unmatchedCount: number;
  matchedFileCount: number;
  skippedFiles: string[];
  message?: string;
  uploadSummary?: string;
};

type SpawnResult = {
  exited: Promise<number>;
  stdout: unknown;
  stderr: unknown;
};

type SpawnRunner = (args: string[]) => SpawnResult;

type UploadSourceSnapshot = {
  sourceDir: string;
  fileCount: number;
  totalBytes: number;
  feedFilename: string;
  feedExists: boolean;
  sampleFiles: string[];
};

const defaultSpawnRunner: SpawnRunner = (args) =>
  Bun.spawn(args, { stdout: "pipe", stderr: "pipe" }) as unknown as SpawnResult;

let uploadInProgress = false;

export const getPodcastFeedConfig = (): PodcastFeedConfig => ({
  publicBaseUrl: (env.PODRUSH_PUBLIC_BASE_URL || "").trim(),
  feedFilename: sanitizeFeedFilename(env.PODRUSH_FEED_FILENAME || DEFAULT_FEED_FILENAME),
  feedTitle: (env.PODRUSH_FEED_TITLE || DEFAULT_FEED_TITLE).trim() || DEFAULT_FEED_TITLE,
  feedDescription:
    (env.PODRUSH_FEED_DESCRIPTION || DEFAULT_FEED_DESCRIPTION).trim() ||
    DEFAULT_FEED_DESCRIPTION,
  uploadTarget: (env.PODRUSH_UPLOAD_TARGET || "").trim(),
});

export const sanitizeFeedFilename = (filename: string): string => {
  const clean = basename(filename.trim()).replace(/[^a-zA-Z0-9._-]/g, "-");
  if (!clean) return DEFAULT_FEED_FILENAME;
  return clean.toLowerCase().endsWith(".xml") ? clean : `${clean || DEFAULT_FEED_FILENAME}.xml`;
};

export const xmlEscape = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");

export const formatSpeedLabel = (speed: number) => speed.toFixed(2).replace(/\.?0+$/, "");

export const parseConvertedPodcastFilename = (filename: string) => {
  const match = filename.match(/-id(\d+)-([0-9.]+)x\.mp3$/i);
  if (!match) return null;
  const episodeId = Number(match[1]);
  const speed = Number(match[2]);
  if (!Number.isFinite(episodeId) || !Number.isFinite(speed)) return null;
  return { episodeId, speed, speedLabel: formatSpeedLabel(speed) };
};

const normalizePublicBaseUrl = (publicBaseUrl: string): string =>
  publicBaseUrl.trim().replace(/\/+$/, "");

export const buildPublicFileUrl = (publicBaseUrl: string, filename: string): string => {
  const base = normalizePublicBaseUrl(publicBaseUrl);
  if (!base) return encodeURIComponent(filename);
  return `${base}/${encodeURIComponent(filename)}`;
};

export const listConvertedPodcastFiles = (convertedDir = CONVERTED_DIR) => {
  let entries: string[] = [];
  try {
    entries = readdirSync(convertedDir);
  } catch {
    return { files: [] as ConvertedPodcastFile[], skippedFiles: [] as string[] };
  }

  const files: ConvertedPodcastFile[] = [];
  const skippedFiles: string[] = [];
  for (const filename of entries) {
    if (!filename.toLowerCase().endsWith(".mp3")) continue;
    const path = join(convertedDir, filename);
    let stat;
    try {
      stat = statSync(path);
    } catch {
      skippedFiles.push(filename);
      continue;
    }
    if (!stat.isFile()) continue;

    const parsed = parseConvertedPodcastFilename(filename);
    if (!parsed) {
      skippedFiles.push(filename);
      continue;
    }

    files.push({
      filename,
      path,
      episodeId: parsed.episodeId,
      speed: parsed.speed,
      speedLabel: parsed.speedLabel,
      size: stat.size,
      mtime: stat.mtime,
    });
  }

  files.sort((a, b) => b.mtime.getTime() - a.mtime.getTime() || a.filename.localeCompare(b.filename));
  skippedFiles.sort((a, b) => a.localeCompare(b));
  return { files, skippedFiles };
};

const metadataForEpisode = (episodeId: number): PodcastEpisodeMetadata | null =>
  (selectPodcastEpisodeMetadata.get(episodeId) as PodcastEpisodeMetadata | undefined) ?? null;

export const buildPodcastFeedItems = (
  files: ConvertedPodcastFile[],
  publicBaseUrl: string,
  lookupMetadata: (episodeId: number) => PodcastEpisodeMetadata | null = metadataForEpisode
): PodcastFeedItem[] => {
  const items: PodcastFeedItem[] = [];
  for (const file of files) {
    const metadata = lookupMetadata(file.episodeId);
    if (!metadata) continue;
      const episodeTitle = metadata.episode_title || `Episode ${file.episodeId}`;
      const feedTitle = metadata.feed_title || DEFAULT_FEED_TITLE;
      const descriptionParts = [
        plainText(metadata.episode_description || ""),
        `Source: ${feedTitle}`,
        `Speed: ${file.speedLabel}x`,
      ].filter(Boolean);
      const published = metadata.published_at ? new Date(metadata.published_at) : null;
      const pubDate =
        published && !Number.isNaN(published.getTime())
          ? published
          : file.mtime;
      const originalDuration = metadata.duration_secs;
      const durationSecs =
        originalDuration !== null &&
        Number.isFinite(originalDuration) &&
        originalDuration > 0 &&
        file.speed > 0
          ? Math.round(originalDuration / file.speed)
          : null;
      items.push({
        ...file,
        title: `${episodeTitle} (${file.speedLabel}x)`,
        description: descriptionParts.join("\n\n"),
        pubDate,
        enclosureUrl: buildPublicFileUrl(publicBaseUrl, file.filename),
        guid: `podrush:${file.filename}`,
        durationSecs,
        metadata,
      });
  }
  return items.sort(
    (a, b) => b.pubDate.getTime() - a.pubDate.getTime() || a.filename.localeCompare(b.filename)
  );
};

export const ensureFeedCoverImage = (convertedDir = CONVERTED_DIR): string | null => {
  let sourceStat;
  try {
    sourceStat = statSync(FEED_COVER_SOURCE_PATH);
  } catch {
    return null;
  }
  if (!sourceStat.isFile()) return null;

  const targetPath = join(convertedDir, FEED_COVER_FILENAME);
  try {
    const targetStat = statSync(targetPath);
    if (targetStat.isFile() && targetStat.mtimeMs >= sourceStat.mtimeMs) {
      return FEED_COVER_FILENAME;
    }
  } catch {
    // Missing target: copy below.
  }

  try {
    copyFileSync(FEED_COVER_SOURCE_PATH, targetPath);
  } catch (err) {
    log("Failed to copy feed cover image", {
      source: FEED_COVER_SOURCE_PATH,
      target: targetPath,
      message: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
  return FEED_COVER_FILENAME;
};

export const renderPodcastRss = (
  items: PodcastFeedItem[],
  config: Pick<PodcastFeedConfig, "feedTitle" | "feedDescription" | "publicBaseUrl" | "feedFilename"> & {
    coverFilename?: string | null;
  }
): string => {
  const now = new Date().toUTCString();
  const feedUrl = buildPublicFileUrl(config.publicBaseUrl, config.feedFilename);
  const coverUrl = config.coverFilename
    ? buildPublicFileUrl(config.publicBaseUrl, config.coverFilename)
    : null;
  const coverXml = coverUrl
    ? `    <image>
      <url>${xmlEscape(coverUrl)}</url>
      <title>${xmlEscape(config.feedTitle)}</title>
      <link>${xmlEscape(feedUrl)}</link>
    </image>
    <itunes:image href="${xmlEscape(coverUrl)}"/>
`
    : "";
  const itemXml = items
    .map((item) => `    <item>
      <title>${xmlEscape(item.title)}</title>
      <description>${xmlEscape(item.description)}</description>
      <pubDate>${item.pubDate.toUTCString()}</pubDate>
      <guid isPermaLink="false">${xmlEscape(item.guid)}</guid>
      <enclosure url="${xmlEscape(item.enclosureUrl)}" length="${item.size}" type="audio/mpeg"/>${
        item.durationSecs !== null
          ? `
      <itunes:duration>${item.durationSecs}</itunes:duration>`
          : ""
      }
    </item>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>${xmlEscape(config.feedTitle)}</title>
    <description>${xmlEscape(config.feedDescription)}</description>
    <link>${xmlEscape(feedUrl)}</link>
${coverXml}    <lastBuildDate>${now}</lastBuildDate>
    <generator>podrush</generator>
${itemXml}
  </channel>
</rss>
`;
};

export const generatePodcastFeed = (
  message = "RSS regenerated.",
  convertedDir = CONVERTED_DIR,
  lookupMetadata: (episodeId: number) => PodcastEpisodeMetadata | null = metadataForEpisode
): PodcastFeedStatus => {
  const config = getPodcastFeedConfig();
  const { files, skippedFiles } = listConvertedPodcastFiles(convertedDir);
  const items = buildPodcastFeedItems(files, config.publicBaseUrl, lookupMetadata);
  const feedPath = join(convertedDir, config.feedFilename);
  const tempPath = `${feedPath}.${process.pid}.tmp`;
  const coverFilename = ensureFeedCoverImage(convertedDir);
  const xml = renderPodcastRss(items, { ...config, coverFilename });

  try {
    writeFileSync(tempPath, xml, "utf8");
    renameSync(tempPath, feedPath);
  } catch (err) {
    try {
      unlinkSync(tempPath);
    } catch {
      // Ignore cleanup errors after failed atomic write.
    }
    throw err;
  }

  return {
    feedPath,
    feedFilename: config.feedFilename,
    publicFeedUrl: buildPublicFileUrl(config.publicBaseUrl, config.feedFilename),
    publicBaseUrl: config.publicBaseUrl,
    configuredPublicBaseUrl: Boolean(config.publicBaseUrl),
    uploadTarget: config.uploadTarget,
    configuredUploadTarget: Boolean(config.uploadTarget),
    generatedAt: new Date().toISOString(),
    itemCount: items.length,
    unmatchedCount: skippedFiles.length + files.length - items.length,
    matchedFileCount: files.length,
    skippedFiles,
    message,
  };
};

export const buildRsyncArgs = (sourceDir: string, uploadTarget: string): string[] => {
  const source = sourceDir.endsWith("/") ? sourceDir : `${sourceDir}/`;
  return [
    "rsync",
    "-av",
    "--delete",
    "--exclude",
    ".DS_Store",
    "--exclude",
    ".*.??????",
    source,
    uploadTarget,
  ];
};

const shellQuote = (value: string): string => {
  if (/^[A-Za-z0-9_/:=.,@%+-]+$/.test(value)) return value;
  return `'${value.replace(/'/g, "'\\''")}'`;
};

const formatCommand = (args: string[]): string => args.map(shellQuote).join(" ");

const collectUploadSourceSnapshot = (
  sourceDir: string,
  feedFilename: string
): UploadSourceSnapshot => {
  const snapshot: UploadSourceSnapshot = {
    sourceDir,
    fileCount: 0,
    totalBytes: 0,
    feedFilename,
    feedExists: false,
    sampleFiles: [],
  };

  let entries: string[] = [];
  try {
    entries = readdirSync(sourceDir).sort((a, b) => a.localeCompare(b));
  } catch {
    return snapshot;
  }

  for (const filename of entries) {
    if (filename === ".DS_Store") continue;
    const path = join(sourceDir, filename);
    let stat;
    try {
      stat = statSync(path);
    } catch {
      continue;
    }
    if (!stat.isFile()) continue;

    snapshot.fileCount += 1;
    snapshot.totalBytes += stat.size;
    if (filename === feedFilename) snapshot.feedExists = true;
    if (snapshot.sampleFiles.length < 8) snapshot.sampleFiles.push(filename);
  }

  return snapshot;
};

const formatUploadDebugSummary = (
  args: string[],
  snapshot: UploadSourceSnapshot,
  exitCode: number,
  stdout: string,
  stderr: string
): string => {
  const lines = [
    `Command: ${formatCommand(args)}`,
    `Source: ${snapshot.sourceDir} (${snapshot.fileCount} files, ${snapshot.totalBytes} bytes)`,
    `Feed file: ${snapshot.feedFilename} (${snapshot.feedExists ? "present" : "missing"})`,
    `Exit code: ${exitCode}`,
  ];
  if (snapshot.sampleFiles.length) {
    lines.push(`Sample files: ${snapshot.sampleFiles.join(", ")}`);
  }
  if (stdout.trim()) {
    lines.push("", "stdout:", stdout.trim());
  }
  if (stderr.trim()) {
    lines.push("", "stderr:", stderr.trim());
  }
  return lines.join("\n").slice(0, 4000);
};

const bodyText = async (body: unknown): Promise<string> => {
  if (!body) return "";
  return new Response(body as any).text();
};

export const uploadConvertedMedia = async (
  status: PodcastFeedStatus,
  runner: SpawnRunner = defaultSpawnRunner
): Promise<PodcastFeedStatus> => {
  const config = getPodcastFeedConfig();
  if (!config.uploadTarget) {
    log("Podcast upload skipped", { reason: "missing PODRUSH_UPLOAD_TARGET" });
    return { ...status, message: "Upload target is not configured." };
  }
  if (uploadInProgress) {
    log("Podcast upload skipped", { reason: "upload already in progress" });
    return {
      ...status,
      message: "Upload already in progress.",
      uploadSummary:
        "Another upload is still running. Wait for it to finish before starting a new upload.",
    };
  }

  const args = buildRsyncArgs(CONVERTED_DIR, config.uploadTarget);
  const snapshot = collectUploadSourceSnapshot(CONVERTED_DIR, config.feedFilename);
  log("Podcast upload starting", {
    command: formatCommand(args),
    sourceDir: snapshot.sourceDir,
    sourceFileCount: snapshot.fileCount,
    sourceTotalBytes: snapshot.totalBytes,
    feedFilename: snapshot.feedFilename,
    feedExists: snapshot.feedExists,
    sampleFiles: snapshot.sampleFiles,
  });

  uploadInProgress = true;
  try {
    const proc = runner(args);
    const [exitCode, stdout, stderr] = await Promise.all([
      proc.exited,
      bodyText(proc.stdout),
      bodyText(proc.stderr),
    ]);
    const summary = formatUploadDebugSummary(args, snapshot, exitCode, stdout, stderr);
    log("Podcast upload finished", {
      exitCode,
      stdoutBytes: stdout.length,
      stderrBytes: stderr.length,
      stdoutPreview: stdout.trim().slice(0, 500),
      stderrPreview: stderr.trim().slice(0, 500),
    });

    if (exitCode !== 0) {
      return {
        ...status,
        message: `Upload failed with exit code ${exitCode}.`,
        uploadSummary: summary,
      };
    }

    return {
      ...status,
      message: "Upload completed.",
      uploadSummary: summary,
    };
  } finally {
    uploadInProgress = false;
  }
};
